### ISSUE TITLE
"Manifest Unknown" while trying to install unpoller on HA/rpi4

### ISSUE THREAD

**Issue by amasolov** [bluemaex/home-assistant-addons#87]
<img width="609" alt="Screenshot 2023-08-07 at 11 50 02 am" src="https://github.com/bluemaex/home-assistant-addons/assets/16586896/6cc5a5e2-ae1f-4f99-8247-4a2845673b63">

**Comment by bluemaex** [comment]
Oh! Someone already found this repository :-)

Hi @amasolov,

Thanks for the report. I just realized i put in a bug with the new deployer workflow that it doesn't push the image to the package repository after building 🙈 

I'll fix this later today and ping you when it's ready 👍

**Comment by amasolov** [comment]
Hi @bluemaex, 

I was very close to make my own add-on and then I found yours. Thank you for your efforts to make it available. I will patiently wait for the fix!

**Comment by bluemaex** [comment]
@amasolov I fixed the issue and also updated to the just released unpoller 2.8.1.

I have used it in my HA Install (also on a RPI4) since a while and works so far flawless. If you find any other issue, please feel free to point them out 👍 

As There is not too much documentation yet, I personally use this with the configuration file approach:

![image](https://github.com/bluemaex/home-assistant-addons/assets/58038/8eadbc57-855c-4059-8c3a-4ee39df88402)


<details>
<summary>Config-File</summary>

```
#
# https://github.com/unpoller/unpoller/blob/master/examples/up.conf.example
#

[influxdb]
  disable = true

[prometheus]
  buffer = 100
  dead_ports = false
  disable = false
  namespace = "unpoller"
  report_errors = true

[unifi.defaults]
  pass = "..."
  url = "..."
  user = "unpoller"
  save_alarms = true
  save_anomalies = true
  save_ids = true
  save_events = true
  save_dpi = true
  sites = [ "default" ]
  verify_ssl = true
```
</details>

**Comment by bluemaex** [comment]
Well I think I was too quick 😬

**Comment by amasolov** [comment]
Working for me too! Thanks!
